### ISSUE TITLE
`if` macro throws when a value is not defined

### ISSUE THREAD

**Issue by jankeromnes** [espadrine/fleau#1]
Scenario:

    <title> Hello {{if title then {{ | }}}}</title>
    
    { }

Expected:

    <title> Hello </title>

Actual (Fleau throws this error):

    Error: Template error: macro "if" didn't work.
    Parameters: title,then, | 
    Literal: {}
    Message: title is not defined
        at Error (native)
        at eval (eval at <anonymous> (/path/to/fleau.js:169:12), <anonymous>:73:9)

**Comment by espadrine** [comment]
Trying to guess beforehand what variables you will expect from the literal (but aren't in it) is way expensive.

From a usability standpoint, `if` is meant to take booleans as conditions. Any other use is a hack. In the current implementation, even `{title:undefined}` would work.

If you want, I can specify in the documentation that you can't use variables that were never referenced in the literal. I expected it to be obvious, as it doesn't work in regular JS either.

```js
> if (title) { console.log(title); }
ReferenceError: title is not defined
```
