### ISSUE TITLE
`SyntaxError: Unexpected identifier` in fleau.js:171:10

### ISSUE THREAD

**Issue by jankeromnes** [espadrine/fleau#3]
Hello! I recently upgraded `camp` from `v16.0.1` to `v16.2.3 ` , which now depends on `fleau 16.0.0`.

I didn't change my routing/template code, and now when I try to access any page from my web app, I get a plain text `404` and this error in the logs:

    SyntaxError: Unexpected identifier
        at Function (native)
        at template (/home/ubuntu/workspace/node_modules/camp/node_modules/fleau/fleau.js:171:10)
        at PassThrough.writer (/home/ubuntu/workspace/node_modules/camp/node_modules/fleau/fleau.js:145:7)
        at emitNone (events.js:72:20)
        at PassThrough.emit (events.js:166:7)
        at endReadableNT (_stream_readable.js:893:12)
        at doNTCallback2 (node.js:429:9)
        at process._tickCallback (node.js:343:17)

Any ideas what I'm doing wrong?

**Comment by espadrine** [comment]
Error reporting is definitely something I lag behind. The new fleau uses a compiler. The error comes from the JS engine's parser. I presume something in the generated code is wrong. Could you provide me with the template, the parameters, and your Node.js version?

**Comment by jankeromnes** [comment]
Actually no, I believe it's the `for` loop:

Template:

    <!doctype html>
    <html lang="en">
      <head>
        <meta charset="utf-8">
        <title> Test </title>
      </head>
      <body>{{ for a in array {{
        <pre>a={{= a in html}}</pre>}}}}
      </body>
    </html>

Parameters:

    { array: ['a','b','c'] }

Node version:

    v6.4.0

**Comment by jankeromnes** [comment]
Fixed by converting the macro to proper JavaScript:

    <body>{{ for (let a of array) { }}
      <pre>a={{= a in html}}</pre>{{ } }}
    </body>

**Comment by espadrine** [comment]
@jankeromnes You should not put a space after `{{`, or it is treated as inserted JS. By default, I recommend using macros rather than inserted JS.

I modified the README to be clearer about that.

**Comment by jankeromnes** [comment]
@espadrine Ok, thanks for the explanation! I thought that the `for` macro stopped being supported in favor of insterted JS.

I wonder why do you recommend macros over JS? Is it because it's safer with less opportunities for errors / side effects?

**Comment by espadrine** [comment]
I have more control over macros. If I wind up offering better error messages, those from macros will provide way more precise information. The drawback, as shown in the readme, is that some complex loops cannot be performed with the macro.
